/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Joke as PrismaJoke } from "@prisma/client";

export class JokeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.JokeCountArgs, "select">): Promise<number> {
    return this.prisma.joke.count(args);
  }

  async jokes(args: Prisma.JokeFindManyArgs): Promise<PrismaJoke[]> {
    return this.prisma.joke.findMany(args);
  }
  async joke(args: Prisma.JokeFindUniqueArgs): Promise<PrismaJoke | null> {
    return this.prisma.joke.findUnique(args);
  }
  async createJoke(args: Prisma.JokeCreateArgs): Promise<PrismaJoke> {
    return this.prisma.joke.create(args);
  }
  async updateJoke(args: Prisma.JokeUpdateArgs): Promise<PrismaJoke> {
    return this.prisma.joke.update(args);
  }
  async deleteJoke(args: Prisma.JokeDeleteArgs): Promise<PrismaJoke> {
    return this.prisma.joke.delete(args);
  }
}
